tnct-spc/ibird

- components/control/ModalUploader.vue
> [fix]modalのクラスが表示されないバグ

- components/control/ControlPanel.vue
> [change]settingのボタン消した

- pages/control/_control.vue
> controlのログインをなくす

- components/Alert.vue
- components/Homeroom.vue
> [fix]alertとqrの位置

- pages/index.vue
> indexにアクセスした時にcontrolへリダイレクトする

- pages/index.vue
> リダイレクト先が良くなかった

- pages/control/_control.vue
Issue番号：
いまさっきのdevelopにある変更をrelease4jに持って行きたかったから一回feature/release4jにdevelopをmergeしてこのpullreqを送る
> 今のdevelopをmergeしただけ

- components/control/ControlPanel.vue
- components/control/ModalUploader.vue
> [change]4j仕様

- server/api/doc/doc-end-time.js
- server/api/doc/index.js
> [add] 終了日を後から変更するAPI

- components/control/ControlUploader.vue
- components/control/ModalUploader.vue
Issue番号： #315 
複数アップロード時modalの設定を引き継ぐようにした
> 複数アップロード時modalの設定を引き継ぐ

- components/control/ControlPanel.vue
inputの大きさ、ボタンを押したかわかるように
Issue番号： #334
> [fix] コントロール画面のalertインターフェース変更

- components/control/ControlSelecter.vue
> [fix]selecter

- components/Homeroom.vue
- components/QR.vue
- middleware/auth.js
- nuxt.config.js
- pages/qrlogin.vue
- server/api/auth/index.js
- server/api/auth/issue-qr-uri.js
- server/index.js
- server/migrations/20181016112203-addQrLoginPasswordToClasses.js
- server/models/classes.js
- server/seeders/20180817073940-classes.js
Issue番号： #260 
一定時間ごとに変わるQRコードを発行してそれでログインできるようにした
データベースを更新しないと動かない
> QRコードでmoiblepageにログインできるようにした

- server/api/alert.js
- server/api/index.js
- server/migrations/20181019035355-addMessageColumnToSchool.js
- server/models/schools.js
- server/seeders/school.js
Issue番号： #345 
何もない場合 message: '' endDate: 0が帰ってくる
時間はunix time 
当然DBを変更したしたのでresetしないと動かない
> alertをDBに乗っけるバックエンド

- components/control/ControlUploader.vue
Issue番号： #351 
uploadするファイルのMIMEタイプのfix
docに対応
> [fix]MIMEタイプ

- server/api/doc/doc-class.js
- server/api/doc/doc.js
- server/api/doc/index.js
Issue番号： #355 
*   設定変更できる要素の現在の状態の取得
* クラス以外の設定変更
*　現在掲示してるクラスの取得
* 掲示クラスの変更
> [add]掲示物の再設定API

- components/BulletinBoard.vue
- components/Paper.vue
- components/control/ModalUploader.vue
- server/api/doc/docs.js
- server/api/upload-file.js
- server/download.js
- server/index.js
- server/migrations/20181020091003-addFilenameColumnToDocuments.js
- server/models/documents.js
issue番号： #340 #341 
そのまま
DBを変更したので
> ファイルダウンロード用urlの作成

- components/Paper.vue
- server/api/upload-file.js
- server/lib/sortdocs.js
> [fix] 画像の解像度を改善

- components/Paper.vue
重なるとややこしいのでクリックしてる間は一番手前に持ってきてる
Issue番号： #368
> [fix]ドラッグしてないのについてくる問題

- components/RainCloud.vue
> [update]天気の座標をアスティ徳島のものに

- components/ViewPaper.vue
> ダブルクリックで拡大するもののサイズが変になる問題

- pages/mobilepage/_hr.vue
> [fix]モバイルページのjpg拡張子を削除

- components/control/ModalUploader.vue
> [fix]modalで指定する掲示物のtitle

- server/seeders/school.js
> [fix]schoolのseed
